name: Check Repository Includes Package
description: Checks VPM repository manifest includes certain package.

inputs:
  repository-filename:
    required: true
    type: string
  package-filename:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Get package properties
      id: manifest
      uses: ./.github/actions/use-package-manifest
      with:
        filename: ${{ inputs.package-filename }}

    - name: Set environment variables
      shell: bash
      run: |
        PKG_NAME="${{ steps.manifest.outputs.name }}"
        PKG_VERSION="${{ steps.manifest.outputs.version }}"

        echo "Package name   : $PKG_NAME"
        echo "Package version: $PKG_VERSION"

        echo "pkg-name=$PKG_NAME" >> $GITHUB_ENV
        echo "pkg-version=$PKG_VERSION" >> $GITHUB_ENV

    - name: Check repository includes package
      shell: bash
      run: |
        QUERY=".packages.\"${{ env.pkg-name }}\".\"${{ env.pkg-version }}\""
        EXPECTED="$(cat "${{ inputs.package-filename }}" | jq -cM ".")"
        ACTUAL="$(cat "${{ inputs.repository-filename }}" | jq -cM "$QUERY")"
        echo "actual  : $ACTUAL"
        echo "expected: $EXPECTED"

        if [ "$ACTUAL" != "$EXPECTED" ]; then
          echo "::error::Package manifest does not match to the one in the repository manifest."
          exit 1
        fi

    - shell: bash
      run: |
        echo "Validation existence of ${{ env.pkg-name }}:${{ env.pkg-version }}: ok" 
