name: Validate Manifest Files

on:
  push:

jobs:
  validate-repository:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/validate-repository-manifest
        with:
          filename: "vpm.json"

  validate-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    strategy:
      matrix:
        path:
          - Assets/Package1
          - Assets/Package2
          - Packages/Package3

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/validate-package-manifest
        with:
          filename: ${{ format('{0}/package.json', matrix.path) }}
          url-pattern: "https://github.com/Tsukina-7mochi/vpm-workflow/releases/download/{name}-v{version}/{name}.v{version}.zip"

      - uses: ./.github/actions/check-repository-includes-package
        with:
          repository: "vpm.json"
          package: "${{ matrix.path }}/package.json"
